=== icelinker/openindy_with_plugins/schema/openIndySchema/openIndySchema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="oiProjectData">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="activeCoordinatesystem">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:byte" name="ref"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="activeStation">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:byte" name="ref"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="stations">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="station">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="activeSensor">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="readingTypes">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="type" maxOccurs="unbounded" minOccurs="0">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:string" name="name" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name"/>
                        <xs:attribute type="xs:string" name="plugin"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="position">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:byte" name="ref"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="coordinatesystem">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:byte" name="ref"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id"/>
                  <xs:attribute type="xs:string" name="name"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="coordinatesystems">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="coordinatesystem" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="expansionOrigin">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:byte" name="x" use="optional"/>
                            <xs:attribute type="xs:byte" name="y" use="optional"/>
                            <xs:attribute type="xs:byte" name="z" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="observations" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="observation" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:byte" name="ref" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id" use="optional"/>
                  <xs:attribute type="xs:string" name="name" use="optional"/>
                  <xs:attribute type="xs:byte" name="solved" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="geometries">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="geometry" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="coordinates">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="x" use="optional"/>
                            <xs:attribute type="xs:float" name="y" use="optional"/>
                            <xs:attribute type="xs:float" name="z" use="optional"/>
                            <xs:attribute type="xs:byte" name="sigmaX" use="optional"/>
                            <xs:attribute type="xs:byte" name="sigmaY" use="optional"/>
                            <xs:attribute type="xs:byte" name="sigmaZ" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="spatialDirection" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="i" use="optional"/>
                            <xs:attribute type="xs:float" name="j" use="optional"/>
                            <xs:attribute type="xs:float" name="k" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="standardDeviation">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="observations" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="observation" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:byte" name="ref" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="measurementconfig">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="name" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="usedFor" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="feature">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:byte" name="ref" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="previouslyNeeded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="feature" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:byte" name="ref" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="functions" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="function">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="inputElements" minOccurs="0">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="inputElement" maxOccurs="unbounded" minOccurs="0">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                              <xs:attribute type="xs:byte" name="index" use="optional"/>
                                              <xs:attribute type="xs:byte" name="type" use="optional"/>
                                              <xs:attribute type="xs:byte" name="ref" use="optional"/>
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="inputElement" maxOccurs="unbounded" minOccurs="0">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:byte" name="index" use="optional"/>
                                        <xs:attribute type="xs:byte" name="type" use="optional"/>
                                        <xs:attribute type="xs:byte" name="ref" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="name" use="optional"/>
                              <xs:attribute type="xs:string" name="type" use="optional"/>
                              <xs:attribute type="xs:string" name="plugin" use="optional"/>
                              <xs:attribute type="xs:byte" name="executionIndex" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id" use="optional"/>
                  <xs:attribute type="xs:string" name="name" use="optional"/>
                  <xs:attribute type="xs:string" name="type" use="optional"/>
                  <xs:attribute type="xs:byte" name="nominal" use="optional"/>
                  <xs:attribute type="xs:byte" name="common" use="optional"/>
                  <xs:attribute type="xs:byte" name="solved" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="observations">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="observation" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="station">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:byte" name="ref" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="reading">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="measurements">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="measurement" maxOccurs="unbounded" minOccurs="0">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:string" name="type" use="optional"/>
                                        <xs:attribute type="xs:float" name="value" use="optional"/>
                                        <xs:attribute type="xs:float" name="sigma" use="optional"/>
                                        <xs:attribute type="xs:time" name="time" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:byte" name="id" use="optional"/>
                        <xs:attribute type="xs:byte" name="type" use="optional"/>
                        <xs:attribute type="xs:dateTime" name="time" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id" use="optional"/>
                  <xs:attribute type="xs:float" name="x" use="optional"/>
                  <xs:attribute type="xs:float" name="y" use="optional"/>
                  <xs:attribute type="xs:float" name="z" use="optional"/>
                  <xs:attribute type="xs:byte" name="isValid" use="optional"/>
                  <xs:attribute type="xs:float" name="sigmaX" use="optional"/>
                  <xs:attribute type="xs:float" name="sigmaY" use="optional"/>
                  <xs:attribute type="xs:float" name="sigmaZ" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name"/>
      <xs:attribute type="xs:dateTime" name="date"/>
      <xs:attribute type="xs:byte" name="idcount"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== icelinker/openindy_with_plugins/schema/tmp/oiProject_test-1.xml
<!-- Autogenerated from CAM template by XSLT (version 2.16) 
                    
                    CAM Template HEADER information: 
                    
                    Description: No Description 
                    Owner: Not Set 
                    Date: 2014-08-04T11:10:33 
                    Version: 0.1 
                    
                    SETTINGS: 
                    Seed: 0.7233482617587541 
                    Hints file: 
                    Optional items:  
                    Choice mode: one
                    Input repeat count: 3
                    Default content:  
                    Random error mode: 
                    Debug mode: false
                    Schema: D:\SoftDev\Qt\openIndy\schema\openIndySchema.xsd
                    Namespace mode: true --><oiProjectData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="D:/SoftDev/Qt/openIndy/schema/openIndySchema.xsd"
               name="string"
               date="string"
               idcount="332720">
   <activeCoordinatesystem ref="793028"/>
   <activeStation ref="1.032334E6"/>
   <stations>
      <station id="561156" name="string">
         <activeSensor name="string" plugin="string">
            <readingTypes>
               <type name="string"/>
            </readingTypes>
         </activeSensor>
         <position ref="763007"/>
         <coordinatesystem ref="547048"/>
      </station>
      <station id="1.027472E6" name="string">
         <activeSensor name="string" plugin="string">
            <readingTypes>
               <type name="string"/>
               <type name="string"/>
            </readingTypes>
         </activeSensor>
         <position ref="219534"/>
         <coordinatesystem ref="1.061597E6"/>
      </station>
      <station id="1.136994E6" name="string">
         <activeSensor name="string" plugin="string">
            <readingTypes>
               <type name="string"/>
            </readingTypes>
         </activeSensor>
         <position ref="760299"/>
         <coordinatesystem ref="72603"/>
      </station>
   </stations>
   <coordinatesystems>
      <coordinatesystem id="426155" name="string" solved="false"/>
      <coordinatesystem id="406168" name="string" solved="false"/>
      <coordinatesystem id="27284" name="string" solved="false"/>
   </coordinatesystems>
   <geometries>
      <geometry id="895572" name="string" type="string" nominal="false" common="false"
                solved="false">
         <coordinates x="31.02" y="71.73" z="70.6" sigmaX="97.57" sigmaY="45.02" sigmaZ="90.33"/>
         <standardDeviation value="28.09"/>
      </geometry>
   </geometries>
</oiProjectData>

=== icelinker/openindy_with_plugins/schema/tmp/oiProject_test-3.xml
<!-- Autogenerated from CAM template by XSLT (version 2.16) 
                    
                    CAM Template HEADER information: 
                    
                    Description: No Description 
                    Owner: Not Set 
                    Date: 2014-08-04T11:10:33 
                    Version: 0.1 
                    
                    SETTINGS: 
                    Seed: 0.7233482617587541 
                    Hints file: 
                    Optional items:  
                    Choice mode: one
                    Input repeat count: 3
                    Default content:  
                    Random error mode: 
                    Debug mode: false
                    Schema: D:\SoftDev\Qt\openIndy\schema\openIndySchema.xsd
                    Namespace mode: true --><oiProjectData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="D:/SoftDev/Qt/openIndy/schema/openIndySchema.xsd"
               name="string"
               date="string"
               idcount="875673">
   <activeCoordinatesystem ref="1.029017E6"/>
   <activeStation ref="971094"/>
   <stations>
      <station id="774343" name="string">
         <activeSensor name="string" plugin="string">
            <readingTypes>
               <type name="string"/>
               <type name="string"/>
            </readingTypes>
         </activeSensor>
         <position ref="1.233953E6"/>
         <coordinatesystem ref="1.112601E6"/>
      </station>
   </stations>
   <coordinatesystems>
      <coordinatesystem id="1.038907E6" name="string" solved="false"/>
      <coordinatesystem id="178654" name="string" solved="false"/>
      <coordinatesystem id="438955" name="string" solved="false"/>
   </coordinatesystems>
   <geometries>
      <geometry id="24822" name="string" type="string" nominal="false" common="false"
                solved="false">
         <coordinates x="79.41" y="117.66" z="46.9" sigmaX="19.5" sigmaY="6.07" sigmaZ="13.02"/>
         <standardDeviation value="52.44"/>
      </geometry>
   </geometries>
</oiProjectData>
